name = "advanced-en-6th"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "advanced-en-6th"

[build]
command = "npm run build"
cwd = "."
watch_dir = "docs"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9"

pages_build_output_dir = "docs/.vuepress/dist" 